package eu.cec.digit.apps.meta.messages.crud.search.request.oracle;

import java.beans.PropertyDescriptor;
import java.util.Date;

import com.business.apps.core.data.search.criteria.LogicalOperator;
import com.business.apps.core.data.search.criteria.Operator;
import com.business.apps.core.data.search.criteria.Predicate;



/**
 * the first operand generated by this criteria will look like : TRUNC(field)
 * instead of field
 * 
 * @author Liviu Gabriel Cretu
 * 
 */
public class PredicateOracleString extends Predicate {

	private static final String P = ")";
	private static final String UPPER_CASE = "UPPER(";
	/**
	 * 
	 */
	private static final long serialVersionUID = -5424229416280726462L;
	public PredicateOracleString(){}
	
	public PredicateOracleString(LogicalOperator logicalOperator,
			PropertyDescriptor field, Operator operator, Object value) {
		super(logicalOperator, field, operator, value);
		if (!checkPropertyDate(field))
			throw new IllegalArgumentException("This one is intended for Strings only!");
	}

	private boolean checkPropertyDate(PropertyDescriptor field) {
		return String.class.equals(field.getPropertyType());
		
	}

	public PredicateOracleString(PropertyDescriptor field,
			Operator operator, Object value) {
		super(field, operator, value);
		if (!checkPropertyDate(field))
			throw new IllegalArgumentException("This one is intended for Strings only!");
	}

	@Override
	protected String getOperand1() {
		// TODO Auto-generated method stub
		return UPPER_CASE+super.getOperand1()+P;
	}

	@Override
	public Object getValue() {
		Object val = super.getValue();
		if (val != null){
			return ((String)val).toUpperCase();
		} else {
			return val;
		}
	}
}
